apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zb2kzx9f6-python
  janus-idp.io/tekton: zb2kzx9f6-python
  backstage.io/kubernetes-id: zb2kzx9f6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zb2kzx9f6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
